In [ ]:
# Install Plotly library for data visualization
!pip install plotly

Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.2)

In [ ]:
# Import pandas for data handling
import pandas as pd

# Import numpy for numerical operations
import numpy as np

# Import plotly for visualizations
import plotly.express as px

# Import train_test_split for splitting data
from sklearn.model_selection import train_test_split

# Import Linear Regression model
from sklearn.linear_model import LinearRegression

# Import evaluation metrics
from sklearn.metrics import mean_absolute_error, r2_score

In [ ]:
# Create dataset using dictionary

data = {
    "Study_Hours":[1,2,3,4,5,6,7,8,9,10,11,12],
    "Attendance":[60,65,70,72,75,80,82,85,88,90,92,95],
    "Assignments":[2,3,4,5,5,6,7,7,8,8,9,10],
    "Marks":[35,40,45,50,58,65,72,78,82,88,92,96]
}

# Convert dictionary into DataFrame
df = pd.DataFrame(data)

# Save dataset as CSV file
df.to_csv("student_performance.csv", index=False)

# Display confirmation message
print("Dataset Created Successfully")

Dataset Created Successfully

In [ ]:
# Load CSV dataset using pandas
df = pd.read_csv("student_performance.csv")

# Display dataset
df

    Study_Hours  Attendance  Assignments  Marks
0             1          60            2     35
1             2          65            3     40
2             3          70            4     45
3             4          72            5     50
4             5          75            5     58
5             6          80            6     65
6             7          82            7     72
7             8          85            7     78
8             9          88            8     82
9            10          90            8     88
10           11          92            9     92
11           12          95           10     96

In [ ]:
# Display first 5 rows of dataset
df.head()
# Display last 5 rows of dataset
df.tail()
# Display number of rows and columns
df.shape
# Display all column names
df.columns
# Display data types of columns
df.dtypes
# Display statistical summary
df.describe()

       Study_Hours  Attendance  Assignments      Marks
count    12.000000   12.000000    12.000000  12.000000
mean      6.500000   79.500000     6.166667  66.750000
std       3.605551   11.172206     2.443296  21.080474
min       1.000000   60.000000     2.000000  35.000000
25%       3.750000   71.500000     4.750000  48.750000
50%       6.500000   81.000000     6.500000  68.500000
75%       9.250000   88.500000     8.000000  83.500000
max      12.000000   95.000000    10.000000  96.000000

In [ ]:
# Features (Input Variables)
X = df[["Study_Hours", "Attendance", "Assignments"]]

# Label (Target Variable)
y = df["Marks"]

# Display features
print("Features:")
print(X)

# Display label
print("\nLabel:")
print(y)

Features:
    Study_Hours  Attendance  Assignments
0             1          60            2
1             2          65            3
2             3          70            4
3             4          72            5
4             5          75            5
5             6          80            6
6             7          82            7
7             8          85            7
8             9          88            8
9            10          90            8
10           11          92            9
11           12          95           10

Label:
0     35
1     40
2     45
3     50
4     58
5     65
6     72
7     78
8     82
9     88
10    92
11    96
Name: Marks, dtype: int64

In [ ]:
# Split dataset into training and testing data

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,     # 20% testing data
    random_state=42    # For reproducible output
)

# Display shapes
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (9, 3)
X_test shape: (3, 3)
y_train shape: (9,)
y_test shape: (3,)

In [ ]:
# Create Linear Regression model
model = LinearRegression()

In [ ]:
# Train the model using training data
model.fit(X_train, y_train)

# Display success message
print("Model Trained Successfully")

Model Trained Successfully

In [ ]:
# Display coefficients (slopes)
print("Slope / Coefficients:")
print(model.coef_)

# Display intercept
print("\nIntercept:")
print(model.intercept_)

Slope / Coefficients:
[ 3.45487968  1.34491979 -2.40274064]

Intercept:
-48.100601604278054

In [ ]:
# Predict marks using testing data
y_pred = model.predict(X_test)

# Display predictions
print(y_pred)

[92.01102941 88.2690508  31.24398396]

In [ ]:
# Create new student data

new_data = pd.DataFrame({
    "Study_Hours":[5,8,12],
    "Attendance":[80,90,95],
    "Assignments":[5,8,10]
})

# Predict marks
predictions = model.predict(new_data)

# Add predictions to dataframe
new_data["Predicted_Marks"] = predictions

# Display predictions
print(new_data)

   Study_Hours  Attendance  Assignments  Predicted_Marks
0            5          80            5        64.753676
1            8          90            8        81.359291
2           12          95           10        97.097928

In [ ]:
# Create comparison dataframe

comparison = pd.DataFrame({
    "Actual Marks": y_test,
    "Predicted Marks": y_pred
})

# Calculate difference
comparison["Difference"] = abs(
    comparison["Actual Marks"] -
    comparison["Predicted Marks"]
)

# Display comparison table
print(comparison)

    Actual Marks  Predicted Marks  Difference
10            92        92.011029    0.011029
9             88        88.269051    0.269051
0             35        31.243984    3.756016

In [ ]:
# Find maximum prediction error
max_error = comparison["Difference"].max()

# Display student with highest error
highest_error = comparison[
    comparison["Difference"] == max_error
]

print(highest_error)

   Actual Marks  Predicted Marks  Difference
0            35        31.243984    3.756016

In [ ]:
# Calculate Mean Absolute Error
mae = mean_absolute_error(y_test, y_pred)

# Display MAE
print("Mean Absolute Error:", mae)

Mean Absolute Error: 1.3453654188948245

In [ ]:
# Calculate R² Score
r2 = r2_score(y_test, y_pred)

# Display R² Score
print("R² Score:", r2)

R² Score: 0.9929962957709836

In [ ]:
# Create scatter plot with hover data

fig = px.scatter(
    df,
    x="Attendance",
    y="Marks",
    hover_data=["Study_Hours", "Assignments"],
    title="Attendance vs Marks"
)

# Display plot
fig.show()

In [ ]:
# Create colored scatter plot

fig = px.scatter(
    df,
    x="Assignments",
    y="Marks",
    color="Assignments",
    title="Assignments vs Marks"
)

# Display plot
fig.show()

In [ ]:
# Create regression line plot

fig = px.scatter(
    df,
    x="Study_Hours",
    y="Marks",
    trendline="ols",
    title="Regression Line Visualization"
)

# Display plot
fig.show()

In [ ]:
# Create future study hours

hours = list(range(1,16))

# Create dataframe for predictions
future_data = pd.DataFrame({
    "Study_Hours": hours,
    "Attendance": [80]*15,
    "Assignments": [5]*15
})

# Predict future marks
future_predictions = model.predict(future_data)

# Create trend dataframe
trend_df = pd.DataFrame({
    "Study_Hours": hours,
    "Predicted_Marks": future_predictions
})

# Create line chart
fig = px.line(
    trend_df,
    x="Study_Hours",
    y="Predicted_Marks",
    title="Predicted Marks Trend"
)

# Display chart
fig.show()

In [ ]:
# Save comparison table as CSV
comparison.to_csv("comparison_output.csv", index=False)

print("Comparison File Saved")

Comparison File Saved